import { markRaw } from "vue";

import { ComputedDefinitionType, WatchersType } from "@ui/version_3/types/base_type";

import { ContentCardUIPropsInterface } from "@ui/version_3/ui_types/content_card_ui_type";

import {
    TransactionReceiptViewComponentsInterface,
    TransactionReceiptViewComputedDataInterface,
    TransactionReceiptViewContentInterface,
    TransactionReceiptViewPropsInterface,
    TransactionReceiptViewStateDataInterface
} from "@/ui_types/transaction_receipt_view_type";

import { TransactionReceiptRecordInterface } from "@/types/api_service_type";

import ContentCardUI from "@ui/version_3/components/ContentCardUI.vue";

import PaginationUI from "@ui/version_3/components/PaginationUI.vue";

import BaseController from "@ui/version_3/base_classes/base_controller";

import ContentManagerUtil from "@ui/version_3/utils/content_manager_util";

import DisplayFormatterUtil from "@/utils/display_formatter_util";

import ContentCardHTMLClassStyles from "@/class_styles/content_card_html_class_styles";

import MemberAuthenticatorUtil from "@/utils/member_authenticator_util";

import PaginationUIPropsBuilder from "@ui/version_3/props_builder/pagination_ui_props_builder";

import ContentCardUIPropsBuilder from "@ui/version_3/props_builder/content_card_ui_props_builder";

import TransactionReceiptViewActionHandler from "@/action_handlers/transaction/receipt_view_action_handler";

import TransactionReceiptViewClassStyles from "@/class_styles/transaction_receipt_view_class_styles";

import { EventBus } from "@/utils/global_event_bus_util";

import { GlobalEventTypes } from "@/types/global_events_type";

class TransactionReceiptViewController extends BaseController<
    TransactionReceiptViewPropsInterface,
    TransactionReceiptViewStateDataInterface,
    TransactionReceiptViewComputedDataInterface,
    TransactionReceiptViewComponentsInterface,
    GlobalEventTypes
> {
    public action_handler: TransactionReceiptViewActionHandler;

    public readonly class_styles = TransactionReceiptViewClassStyles;

    private readonly content_manager = ContentManagerUtil.getInstance();

    private readonly base_content_key = "content_resource.transaction_view_ui.profile_view_ui.receipts_view";

    // Method to initialise the independently paginated transaction receipts tab.
    constructor(props: TransactionReceiptViewPropsInterface) {
        super("transaction_receipt_view", props, EventBus);

        this.action_handler = new TransactionReceiptViewActionHandler(this);
        this.setActionHandler(this.action_handler);
    }

    // Method to resolve receipt content with a local fallback.
    private getContent(key: string, fallback: string): string {
        return this.content_manager.get<string>(key, fallback) ?? fallback;
    }

    // Method to build the receipt tab's content object.
    private getContentObject(): TransactionReceiptViewContentInterface {
        const base = this.base_content_key;

        return {
            loading_text: this.getContent(`${base}.loading_text`, "Loading receipts..."),
            empty_state_text: this.getContent(`${base}.empty_state_text`, "No receipts found for this transaction."),
            search_placeholder_text: this.getContent(`${base}.search_placeholder_text`, "Search receipts"),
            view_receipt_btn_text: this.getContent(`${base}.view_receipt_btn_text`, "View Receipt"),
            receipt_unavailable_text: this.getContent(`${base}.receipt_unavailable_text`, "Receipt file unavailable"),
            permission_denied_text: this.getContent(
                `${base}.permission_denied_text`,
                "You do not have permission to view transaction receipts."
            ),
            pagination_result_text: this.getContent(
                `${base}.pagination_result_text`,
                "Page {{current_page}} of {{total_pages}} ({{total_items}} receipts)"
            ),
            labels: {
                receipt_number: this.getContent(`${base}.labels.receipt_number`, "Receipt Number"),
                public_id: this.getContent(`${base}.labels.public_id`, "Receipt ID"),
                status: this.getContent(`${base}.labels.status`, "Status"),
                generated_by: this.getContent(`${base}.labels.generated_by`, "Generated By"),
                generated_at: this.getContent(`${base}.labels.generated_at`, "Generated"),
                processor_attempts: this.getContent(`${base}.labels.processor_attempts`, "Processor Attempts"),
                last_error: this.getContent(`${base}.labels.last_error`, "Last Error"),
                created_at: this.getContent(`${base}.labels.created_at`, "Created")
            }
        };
    }

    // Method to expose receipt card and pagination components.
    protected getUIComponents(): TransactionReceiptViewComponentsInterface {
        return {
            ContentCardUI: markRaw(ContentCardUI),
            PaginationUI: markRaw(PaginationUI)
        };
    }

    // Method to initialise receipt records, search, and pagination state.
    protected getUIStateData(): TransactionReceiptViewStateDataInterface {
        const pagination_props = PaginationUIPropsBuilder.getReactivePropsObject(
            "TransactionReceiptsPagination",
            `${this.base_content_key}.pagination_btn_content`,
            1,
            1,
            {
                content_props: {
                    prev_btn_icon: "arrow_left_short_circle_svg_icon",
                    next_btn_icon: "arrow_right_short_cirlce_svg_icon"
                },
                config_props: { show_numbers: true, max_visible_pages: 3 },
                action_props: { on_page_change: this.action_handler.handlePageChange }
            }
        );

        return {
            receipts: [],
            current_page: 1,
            total_pages: 0,
            total_items: 0,
            limit: 6,
            search_query: "",
            is_loading: false,
            content_obj: this.getContentObject(),
            pagination_props
        };
    }

    // Method to format the receipt pagination result copy.
    protected getUIComputedData(): ComputedDefinitionType<TransactionReceiptViewComputedDataInterface> {
        return {
            can_view_receipts: () =>
                MemberAuthenticatorUtil.memberHasPermissionTo("transaction_module.get_transaction_receipt_list"),
            pagination_result_text: () =>
                this.state_refs.content_obj.value.pagination_result_text
                    .replace("{{current_page}}", this.state_refs.current_page.value.toString())
                    .replace("{{total_pages}}", this.state_refs.total_pages.value.toString())
                    .replace("{{total_items}}", this.state_refs.total_items.value.toString())
        };
    }

    // Method to watch receipt search changes and transaction switches.
    protected getUIWatchers(): WatchersType<TransactionReceiptViewPropsInterface, TransactionReceiptViewStateDataInterface> {
        return {
            transaction_id: {
                handler: () => void this.action_handler.fetchReceipts(1),
                options: { immediate: false }
            },
            search_query: this.action_handler.handleSearchQueryChanged
        };
    }

    // Method to load receipts when the receipts tab component mounts.
    protected async handleOnMountedLogic(): Promise<void> {
        await this.action_handler.fetchReceipts(1);
    }

    // Method to clear receipt search resources before unmounting.
    protected async handleBeforeUnmountedLogic(): Promise<void> {
        this.action_handler.cleanup();
    }

    // Method to synchronize pagination component data with receipt state.
    public updatePaginationProps(): void {
        const pagination_props = this.state_refs.pagination_props.value;
        pagination_props.data_props.current_page = this.state_refs.current_page.value;
        pagination_props.data_props.total_pages = this.state_refs.total_pages.value;
        this.state_refs.pagination_props.value = pagination_props;
    }

    // Method to build a safe compact receipt detail badge.
    private buildDescriptionItem(label: string, value?: unknown): string {
        return [
            `<span class="${ContentCardHTMLClassStyles.compact_description_item_class_style}">`,
            `<strong class="${ContentCardHTMLClassStyles.description_label_class_style}">${DisplayFormatterUtil.escapeHtml(label)}:</strong>`,
            `<span>${DisplayFormatterUtil.escapeHtml(value || "-")}</span>`,
            `</span>`
        ].join("");
    }

    // Method to resolve the generating member's display name.
    private getGeneratedBy(receipt: TransactionReceiptRecordInterface): string {
        const member = receipt.generated_by_member;
        return member?.full_name || [member?.first_name, member?.last_name].filter(Boolean).join(" ") || member?.email || "-";
    }

    // Method to build content-card props for a receipt record.
    public getReceiptCardProps(receipt: TransactionReceiptRecordInterface): ContentCardUIPropsInterface {
        const content = this.state_refs.content_obj.value;
        const description = [
            this.buildDescriptionItem(content.labels.public_id, receipt.public_id),
            this.buildDescriptionItem(content.labels.status, DisplayFormatterUtil.formatLabel(receipt.status)),
            this.buildDescriptionItem(content.labels.generated_by, this.getGeneratedBy(receipt)),
            this.buildDescriptionItem(content.labels.generated_at, DisplayFormatterUtil.formatDateTime(receipt.generated_at)),
            this.buildDescriptionItem(content.labels.processor_attempts, receipt.processor_attempts ?? 0),
            receipt.last_error ? this.buildDescriptionItem(content.labels.last_error, receipt.last_error) : "",
            this.buildDescriptionItem(content.labels.created_at, DisplayFormatterUtil.formatDateTime(receipt.created_at))
        ].join("");

        return ContentCardUIPropsBuilder.getReactivePropsObject(`TransactionReceipt${receipt.public_id}`, {
            content_props: {
                title_text: `${content.labels.receipt_number}: ${receipt.receipt_number}`,
                title_icon: "identification_card_svg_icon",
                description_text: description,
                button_text: receipt.receipt_url ? content.view_receipt_btn_text : content.receipt_unavailable_text,
                button_icon: receipt.receipt_url ? "link_square_arrow_top_right_svg_icon" : "x_circile_svg_icon"
            },
            boolean_props: { disabled: !receipt.receipt_url },
            action_props: {
                on_click: async () => this.action_handler.handleViewReceiptClicked(receipt.receipt_url)
            },
            class_styles: this.class_styles.receipt_card_class_styles
        });
    }
}

export default TransactionReceiptViewController;
